### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by obecerra-dimeline** [jacobpieczynski/MLB-Game-Prediction-V2.0#1]
Is there an order to running your scripts or just run main?

**Comment by jacobpieczynski** [comment]
Hi! Main is built to output the combined, test, and train csv's. Train.py (in a few different configurations) builds the model off of these csv's and tests them. So the only files meant to be executable are Main.py and Train.py. Please note these files are in various testing phases and may have some issues/need slight modifications with running.

Thanks for the question, I'll update the documentation to reflect that.
