### ISSUE TITLE
Where is Test.py

### ISSUE THREAD

**Issue by obecerra-dimeline** [jacobpieczynski/MLB-Game-Prediction-V2.0#2]
Sorry,

One last question, I don't see Test.py in your src file, and could you clarify what the output result is? is it a game predictor for the current games/season or last?

Thanks again!

**Comment by jacobpieczynski** [comment]
I totally misspoke, it should be train.py. Sorry about that. The goal is for it to be able to input an individual game and use the model to predict the outcome. Currently, all it does is train the model and print various tests I'm currently running. The .txt files in the repo are the outputs of many of these tests.
